name: 'Jscrambler'
description: 'Jscrambler Code Integrity Github Action'

inputs:
  secret-key:
    description: 'User Secret Key'
    required: false
  access-key:
    description: 'User Access Key'
    required: false
  jscrambler-config-path:
    description: 'Path to jscrambler configuration'
    default: '.jscramblerrc'
    required: false
  application-id:
    description: 'User Application Id'
    required: false
  files-src:
    description: 'List of file sources (glob patterns allowed)'
    required: false
  files-dest:
    description: 'Output directory/file'
    required: false
  jscrambler-version:
    description: 'Jscramber Version'
    required: false
  protocol:
    description: 'Jscrambler API protocol'
    required: false
  host:
    description: 'Jscrambler API host'
    required: false
  port:
    description: 'Jscrambler API port'
    required: false
  base-path:
    description: 'Jscrambler API base path'
    required: false

  # DEBUG
  source-maps-output-path:
    description: 'Source Maps Output Path -- The source maps are stored as files inside a jscramblerSourceMaps folder here'
    required: false
  debug-mode:
    description: 'Set Debug Mode'
    required: false
    type: boolean

outputs:
  protection-id:
    description: 'Protection Id'

runs:
  using: 'node16'
  main: 'packages/jscrambler-github-action/dist/index.js'
