on: [push]

jobs:
  github_action_test:
    runs-on: ubuntu-latest
    name: Test Protection
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Test Jscrambler Action
        id: jscrambler
        uses: ./
        with:
          application-id: ${{ secrets.JSCRAMBLER_APPLICATION_ID }}
          secret-key: ${{ secrets.JSCRAMBLER_SECRET_KEY }}
          access-key: ${{ secrets.JSCRAMBLER_ACCESS_KEY }}
          jscrambler-config-path: packages/jscrambler-github-action/test-config.json
          files-src: |
            packages/jscrambler-cli/src/index.js
            packages/jscrambler-cli/src/config.js
          files-dest: dist/
          source-maps-output-path: dist-extra/
          symbol-table-output-path: dist-extra/symbols/
      # Use the output from the `hello` step
      - name: Get the output protection_id
        run: echo "Your protection was successful. ${{ steps.jscrambler.outputs.protection-id }}"
      - name: Upload protected code
        uses: actions/upload-artifact@v3
        with:
          name: protected-source-code
          path: dist/
          retention-days: 1
      - name: Upload symbol table
        uses: actions/upload-artifact@v3
        with:
          name: symbols
          path: dist-extra/symbols/
          retention-days: 1
      - name: Upload source maps
        uses: actions/upload-artifact@v3
        with:
          name: source-maps
          path: dist-extra/jscramblerSourceMaps/
          retention-days: 1
  test:
    runs-on: ubuntu-latest
    name: Test Protection
    steps:
      - uses: actions/checkout@v3
      - name: Test Jscrambler Action
        id: jscrambler
        uses: ./
        run: lerna exec --scope jscrambler-github-action "npm run test"