on: [push]

jobs:
  jscrambler_job:
    runs-on: ubuntu-latest
    name: A job to obfuscate code
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Test Jscrambler Action
        id: jscrambler
        uses: ./
        with:
          application-id: ${{ secrets.JSCRAMBLER_APPLICATION_ID }}
          secret-key: ${{ secrets.JSCRAMBLER_SECRET_KEY }}
          access-key: ${{ secrets.JSCRAMBLER_ACCESS_KEY }}
          jscrambler-config-path: packages/jscrambler-github-action/test-config.json
          files-src: |
            packages/jscrambler-cli/src/index.js
            packages/jscrambler-cli/src/config.js
          files-dest: dist/
      # Use the output from the `hello` step
      - name: Get the output protection_id
        run: echo "Your protection was successful. ${{ steps.jscrambler.outputs.protection-id }}"
