name: Release Github Action

on:
  push:
    tags:
      - '*'

jobs:
  publish_code_integrity_github_action:
    runs-on: ubuntu-latest
    name: Publish Jscrambler Code Integrity GitHub Action
    steps:
      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.CODE_INTEGRITY_ACTIONS_APP_ID }}
          application_private_key: ${{ secrets.CODE_INTEGRITY_ACTIONS_PRIVATE_KEY }}
      - uses: actions/checkout@v3
        with:
          repository: jscrambler/jscrambler-github-action
          token: ${{ steps.get_workflow_token.outputs.token }}
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
      - name: Update Jscrambler CLI Version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: dependencies.jscrambler
          # value: ${{ steps.tagName.outputs.tag }}
          value: 6.2.8
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump Jscrambler to ${{ steps.tagName.outputs.tag }}
          commit_user_name: Jscrambler
          commit_user_email: code@jscrambler.com
          commit_author: Jscrambler <code@jscrambler.com>
          tagging_message: ${{ steps.tagName.outputs.tag }}