on:
  push:
    tags:
      - '*'

jobs:
  publish_github_action:
    runs-on: ubuntu-latest
    name: Publish GitHub Action
    environment: production
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Clone GitHub Action Repository
        run: |
             git clone https://github.com/jscrambler/jscrambler-github-action
      - name: Publish GitHub Action
        run: |
             cd jscrambler-github-action
             gh auth setup-git
             # Update Jscrambler version and build
             PACKAGE_VERSION=6.2.8
             echo $(jq ".dependencies.jscrambler=\"${PACKAGE_VERSION}\"" package.json) > package.json
             npm i
             npm run build
             # Test the package, just in case
             npm t
             # Create new branch, but do not push it
             git checkout -b release-branch
             shopt -s extglob
             rm -rf !(dist|action.tml) .github .gitignore
             # Prepare release
             git tag "${GITHUB_REF_NAME}"
             git push --tags
             # Release
             gh release create "${GITHUB_REF_NAME}"
