on:
  push:
    tags:
      - '*'

jobs:
  publish_github_action:
    runs-on: ubuntu-latest
    name: Publish Jscrambler GitHub Action
    environment: production
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      COMMIT_AUTHOR_NAME: "Jscrambler from GitHub Runner"
      COMMIT_AUTHOR_EMAIL: "code@jscrambler.com"
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jscrambler/jscrambler-github-action
      - uses: olegtarasov/get-tag@v2.1.2
        id: tagName
      - name: Update Jscrambler CLI Version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: package.json
          field: dependencies.jscrambler
          value: ${{ steps.tagName.outputs.tag }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump Jscrambler to ${{ steps.tagName.outputs.tag }}
          commit_user_name: Jscrambler
          commit_user_email: code@jscrambler.com
          commit_author: Jscrambler <code@jscrambler.com>
          tagging_message: ${{ steps.tagName.outputs.tag }}