on:
  push:
    tags:
      - '*'

jobs:
  publish_github_action:
    runs-on: ubuntu-latest
    name: Publish GitHub Action
    steps:
      - uses: actions/checkout@v3
        run:
          - echo $GITHUB_REF_NAME
        
